//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int venta { get; set; }
        public int producto { get; set; }
        public decimal precioVenta { get; set; }
        public decimal cantidad { get; set; }
        public decimal montoProducto { get; set; }
    
        public virtual Producto Producto1 { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
